### ISSUE TITLE
"registerPhone" in .aia

### ISSUE THREAD

**Issue by bbraden** [ajbenz18/Randomly#5]
yo this is a really cool project, it helped me learn how to use API's in mit app inventor. just wondering what the point of the "registerPhone" in the .aia file is for lol. thanks for this project, it was very helpful :D

**Comment by ajbenz18** [comment]
The "registerPhone" screen in the .aia file is for allowing the user to send whatever joke, quote, etc they were shown to someone else via text. The user can type in a phone number or pick someone from their contacts, click send, and it will take the user to their messages app with the text and conversation already loaded. It doesn't actually the send the text, just drafts the text message so the user can then send it themselves. If you want to see how the app behaves, it is on the google play store under the name "Randomly Fun" (may need to search Randomly Fun AJ Bensman for it to show up).

I'm glad this was of use to you! However, my method of getting the content out of the API's response was pretty hacky in hindsight. There are definitely cleaner ways to do it using the json decoder and dictionaries.
